// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckVTExecutable() {
  return window['go']['main']['App']['CheckVTExecutable']();
}

export function ComputeSHA256(arg1) {
  return window['go']['main']['App']['ComputeSHA256'](arg1);
}

export function GetApiKey() {
  return window['go']['main']['App']['GetApiKey']();
}

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function IsContextMenuRegistered() {
  return window['go']['main']['App']['IsContextMenuRegistered']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function RegisterContextMenu() {
  return window['go']['main']['App']['RegisterContextMenu']();
}

export function SaveApiKey(arg1) {
  return window['go']['main']['App']['SaveApiKey'](arg1);
}

export function ScanFile(arg1, arg2) {
  return window['go']['main']['App']['ScanFile'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function UnregisterContextMenu() {
  return window['go']['main']['App']['UnregisterContextMenu']();
}
