// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckVTExecutable():Promise<string>;

export function ComputeSHA256(arg1:string):Promise<string>;

export function GetApiKey():Promise<string>;

export function GetInitialFile():Promise<string>;

export function IsContextMenuRegistered():Promise<boolean>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function RegisterContextMenu():Promise<string>;

export function SaveApiKey(arg1:string):Promise<string>;

export function ScanFile(arg1:string,arg2:boolean):Promise<main.ScanResult>;

export function SelectFile():Promise<string>;

export function UnregisterContextMenu():Promise<string>;
